### ISSUE TITLE
Contact by gateway id

### ISSUE THREAD

**Issue by gerard-mailtrack** [quaderno/quaderno-php#11]
I see the REST API exposes this endpoint (from the documentation).

https://quaderno.io/docs/api/?php#retrieve-get-a-single-contact-by-payment-gateway-id

Apparently, this is not available in the PHP library. 

Is it going to be added any time soon?

**Comment by xxswingxx** [comment]
Hey @gerard-mailtrack , the latest release `1.4.0` should include those methods. Please check it and close this issue if that's enough for you.

**Comment by gerard-mailtrack** [comment]
Works like a charm. 

Thanks!
